### ISSUE TITLE
Couldn't find "libc++_shared.so

### ISSUE THREAD

**Issue by SanjuSudheerM** [eggnstone/eggnstone_amazon_chime#3]
Hi, I'm new to the Flutter. While trying to set it up locally, getting the following error. 
I have copied the libc++_shared.so folder to Android folder as mentioned in the readme.

[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.chimeFlutterPoc-Jj2FFnoO5BJ2sxcSw4ykNQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.chimeFlutterPoc-Jj2FFnoO5BJ2sxcSw4ykNQ==/lib/x86, /data/app/com.example.chimeFlutterPoc-Jj2FFnoO5BJ2sxcSw4ykNQ==/base.apk!/lib/x86, /system/lib]]] couldn't find "libc++_shared.so"

Could you please help me out?

**Comment by eggnstone** [comment]
Did you follow the other step as well ("implementation fileTree ...")?
If yes, then try a "flutter clean" and build again.

**Comment by SanjuSudheerM** [comment]
Yes, I have added ` implementation fileTree(dir: '../libc++_shared.so', include: ['libc++_shared.so.aar'])` in `android/app/build.gradle` also tried the flutter clean and build. 
Facing the same issue.

**Comment by eggnstone** [comment]
Are you trying to let it run on an Android Emulator?
The Amazon Chime SDK does not support x86! 
It only works on ARM i.e. actual Android devices (or ARM emulators, but I had no luck there either).

https://github.com/aws/amazon-chime-sdk-android
"NOTE: Please make sure that you are running on ARM supported devices (real devices) or simulator with arm supported. We do not support x86 currently, so simulators with x86 will not work."

What does work is asking the SDK for it's version, so that's the proof that the connection to the plugin works.
But any other method trigger the load of that library and it's not supported by Chime.

I forgot to document that.
I will update the documentation accordingly.

**Comment by SanjuSudheerM** [comment]
Thanks for your support. Running on an actual device fixed that issue.
